In [2]:
import torch


In [3]:
tz = torch.zeros(2,3)

In [4]:
tz.dtype

torch.float32

In [5]:
tz = torch.zeros(2,3, dtype=torch.int32)

In [6]:
tz = torch.ones(2,3, dtype=torch.long)

In [7]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
torch.eye(3,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [11]:
t = torch.full((2,4), 5)

In [17]:
torch.arange(-5, 0, 2)

tensor([-5, -3, -1])

In [19]:
torch.linspace(1, 5, 8)

tensor([1.0000, 1.5714, 2.1429, 2.7143, 3.2857, 3.8571, 4.4286, 5.0000])

In [20]:
torch.rand(2, 3)

tensor([[0.0230, 0.0463, 0.9648],
        [0.6230, 0.2531, 0.1731]])

In [21]:
torch.randn(2,3)

tensor([[ 1.0942, -1.1499,  0.5100],
        [ 1.1853, -1.4748,  0.7877]])

In [ ]:
torch.manual_seed(12)

In [22]:
a = torch.rand(2, 3)
a.fill_(5)   

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [23]:
a.random_(1,7)

tensor([[4., 3., 5.],
        [3., 5., 4.]])

In [25]:
a.uniform_(0,1)

tensor([[0.8518, 0.5908, 0.6032],
        [0.5028, 0.6997, 0.6740]])

In [27]:
a.normal_(0, 1)

tensor([[ 0.4351, -1.0905, -1.0310],
        [-0.0158,  0.0959, -1.4795]])

In [28]:
torch.cuda.is_available()

False

In [29]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu
