In [1]:
import torch
print(torch.__version__)

2.5.1+cpu


In [3]:
t = torch.Tensor(3, 5, 2)
print(t)

tensor([[[-9.7711e-04,  1.7937e-42],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


In [8]:
t = torch.empty(3,5, 2)

In [6]:
t.dtype

torch.float32

In [7]:
t = torch.empty(3,5,2, dtype=torch.int32)

In [14]:
torch.tensor([[1, 2], [3,4], [5,6]], dtype=torch.float32)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [15]:
torch.IntTensor([1])

tensor([1], dtype=torch.int32)

In [16]:
t = torch.DoubleTensor(3,2,3,5) # 4 osi

In [23]:
d = [[[1,2,3], [4,5,6]]]
t = torch.tensor(d, dtype=torch.float32) 
t.type()
t.dtype
t.dim() # кол-во осей
t.size() # кол-во эл на каждой оси


torch.Size([1, 2, 3])

In [24]:
t.shape

torch.Size([1, 2, 3])

In [25]:
import numpy as np

In [26]:
d_np = np.array([[1,2,3], [4,5,6]])
d_np

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# преобразование в тензор
t2 = torch.from_numpy(d_np) # это типо ссылка изменяя здесь измениться и там
t2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
t3 = torch.tensor(d_np, dtype=torch.float32) # таким мы делаем копию 
t3

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [32]:
# со списками тоже будет копия
d = [[1,2,3], [4,5,6]]
t = torch.IntTensor(d)
tt = torch.tensor(d)

In [34]:
# обратно
d = t2.numpy().copy()
t2.dtype

torch.int64

In [37]:
tf = t2.float()
print(tf)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
